version: '3.0'

services:

  app:
    image: url-shortener
    ports:
      - "8082:8082"
    depends_on:
      - postgres_db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432

  postgres_db:
    image: postgres:13.1-alpine
    container_name: postgres_db
    ports:
       - "5432:5432"
    environment:
       - POSTGRES_DB=test_db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
