spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:users}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082




# JWT TOKEN
jwt:
  token:
    secret-key: secretKey
    expiration: 900000 # 15 minute duration
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
