spring:

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8082



# JWT TOKEN
rsa:
  private-key: ${RSA_PRV}
  public-key: ${RSA_PUB}

client:
  host: ${CLIENT_HOST}